//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.04 at 11:22:45 AM EDT 
//


package org.lumongo.example.medline.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the medline.generated.current package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: medline.generated.current
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AbstractText }
     * 
     */
    public AbstractText createAbstractText() {
        return new AbstractText();
    }

    /**
     * Create an instance of {@link Chemical }
     * 
     */
    public Chemical createChemical() {
        return new Chemical();
    }

    /**
     * Create an instance of {@link LastName }
     * 
     */
    public LastName createLastName() {
        return new LastName();
    }

    /**
     * Create an instance of {@link Month }
     * 
     */
    public Month createMonth() {
        return new Month();
    }

    /**
     * Create an instance of {@link KeywordList }
     * 
     */
    public KeywordList createKeywordList() {
        return new KeywordList();
    }

    /**
     * Create an instance of {@link Keyword }
     * 
     */
    public Keyword createKeyword() {
        return new Keyword();
    }

    /**
     * Create an instance of {@link PersonalNameSubjectList }
     * 
     */
    public PersonalNameSubjectList createPersonalNameSubjectList() {
        return new PersonalNameSubjectList();
    }

    /**
     * Create an instance of {@link PersonalNameSubject }
     * 
     */
    public PersonalNameSubject createPersonalNameSubject() {
        return new PersonalNameSubject();
    }

    /**
     * Create an instance of {@link InvestigatorList }
     * 
     */
    public InvestigatorList createInvestigatorList() {
        return new InvestigatorList();
    }

    /**
     * Create an instance of {@link Investigator }
     * 
     */
    public Investigator createInvestigator() {
        return new Investigator();
    }

    /**
     * Create an instance of {@link OtherAbstract }
     * 
     */
    public OtherAbstract createOtherAbstract() {
        return new OtherAbstract();
    }

    /**
     * Create an instance of {@link MedlineCitation }
     * 
     */
    public MedlineCitation createMedlineCitation() {
        return new MedlineCitation();
    }

    /**
     * Create an instance of {@link PMID }
     * 
     */
    public PMID createPMID() {
        return new PMID();
    }

    /**
     * Create an instance of {@link DateCreated }
     * 
     */
    public DateCreated createDateCreated() {
        return new DateCreated();
    }

    /**
     * Create an instance of {@link DateCompleted }
     * 
     */
    public DateCompleted createDateCompleted() {
        return new DateCompleted();
    }

    /**
     * Create an instance of {@link DateRevised }
     * 
     */
    public DateRevised createDateRevised() {
        return new DateRevised();
    }

    /**
     * Create an instance of {@link Article }
     * 
     */
    public Article createArticle() {
        return new Article();
    }

    /**
     * Create an instance of {@link MedlineJournalInfo }
     * 
     */
    public MedlineJournalInfo createMedlineJournalInfo() {
        return new MedlineJournalInfo();
    }

    /**
     * Create an instance of {@link ChemicalList }
     * 
     */
    public ChemicalList createChemicalList() {
        return new ChemicalList();
    }

    /**
     * Create an instance of {@link SupplMeshList }
     * 
     */
    public SupplMeshList createSupplMeshList() {
        return new SupplMeshList();
    }

    /**
     * Create an instance of {@link CitationSubset }
     * 
     */
    public CitationSubset createCitationSubset() {
        return new CitationSubset();
    }

    /**
     * Create an instance of {@link CommentsCorrectionsList }
     * 
     */
    public CommentsCorrectionsList createCommentsCorrectionsList() {
        return new CommentsCorrectionsList();
    }

    /**
     * Create an instance of {@link GeneSymbolList }
     * 
     */
    public GeneSymbolList createGeneSymbolList() {
        return new GeneSymbolList();
    }

    /**
     * Create an instance of {@link MeshHeadingList }
     * 
     */
    public MeshHeadingList createMeshHeadingList() {
        return new MeshHeadingList();
    }

    /**
     * Create an instance of {@link OtherID }
     * 
     */
    public OtherID createOtherID() {
        return new OtherID();
    }

    /**
     * Create an instance of {@link SpaceFlightMission }
     * 
     */
    public SpaceFlightMission createSpaceFlightMission() {
        return new SpaceFlightMission();
    }

    /**
     * Create an instance of {@link GeneralNote }
     * 
     */
    public GeneralNote createGeneralNote() {
        return new GeneralNote();
    }

    /**
     * Create an instance of {@link Journal }
     * 
     */
    public Journal createJournal() {
        return new Journal();
    }

    /**
     * Create an instance of {@link ISSN }
     * 
     */
    public ISSN createISSN() {
        return new ISSN();
    }

    /**
     * Create an instance of {@link JournalIssue }
     * 
     */
    public JournalIssue createJournalIssue() {
        return new JournalIssue();
    }

    /**
     * Create an instance of {@link DataBank }
     * 
     */
    public DataBank createDataBank() {
        return new DataBank();
    }

    /**
     * Create an instance of {@link AccessionNumberList }
     * 
     */
    public AccessionNumberList createAccessionNumberList() {
        return new AccessionNumberList();
    }

    /**
     * Create an instance of {@link ForeName }
     * 
     */
    public ForeName createForeName() {
        return new ForeName();
    }

    /**
     * Create an instance of {@link Initials }
     * 
     */
    public Initials createInitials() {
        return new Initials();
    }

    /**
     * Create an instance of {@link Suffix }
     * 
     */
    public Suffix createSuffix() {
        return new Suffix();
    }

    /**
     * Create an instance of {@link DescriptorName }
     * 
     */
    public DescriptorName createDescriptorName() {
        return new DescriptorName();
    }

    /**
     * Create an instance of {@link NameID }
     * 
     */
    public NameID createNameID() {
        return new NameID();
    }

    /**
     * Create an instance of {@link DataBankList }
     * 
     */
    public DataBankList createDataBankList() {
        return new DataBankList();
    }

    /**
     * Create an instance of {@link PubDate }
     * 
     */
    public PubDate createPubDate() {
        return new PubDate();
    }

    /**
     * Create an instance of {@link Year }
     * 
     */
    public Year createYear() {
        return new Year();
    }

    /**
     * Create an instance of {@link Day }
     * 
     */
    public Day createDay() {
        return new Day();
    }

    /**
     * Create an instance of {@link Season }
     * 
     */
    public Season createSeason() {
        return new Season();
    }

    /**
     * Create an instance of {@link MedlineDate }
     * 
     */
    public MedlineDate createMedlineDate() {
        return new MedlineDate();
    }

    /**
     * Create an instance of {@link Pagination }
     * 
     */
    public Pagination createPagination() {
        return new Pagination();
    }

    /**
     * Create an instance of {@link StartPage }
     * 
     */
    public StartPage createStartPage() {
        return new StartPage();
    }

    /**
     * Create an instance of {@link EndPage }
     * 
     */
    public EndPage createEndPage() {
        return new EndPage();
    }

    /**
     * Create an instance of {@link MedlinePgn }
     * 
     */
    public MedlinePgn createMedlinePgn() {
        return new MedlinePgn();
    }

    /**
     * Create an instance of {@link ELocationID }
     * 
     */
    public ELocationID createELocationID() {
        return new ELocationID();
    }

    /**
     * Create an instance of {@link DeleteCitation }
     * 
     */
    public DeleteCitation createDeleteCitation() {
        return new DeleteCitation();
    }

    /**
     * Create an instance of {@link AccessionNumber }
     * 
     */
    public AccessionNumber createAccessionNumber() {
        return new AccessionNumber();
    }

    /**
     * Create an instance of {@link ArticleDate }
     * 
     */
    public ArticleDate createArticleDate() {
        return new ArticleDate();
    }

    /**
     * Create an instance of {@link CommentsCorrections }
     * 
     */
    public CommentsCorrections createCommentsCorrections() {
        return new CommentsCorrections();
    }

    /**
     * Create an instance of {@link MedlineCitationSet }
     * 
     */
    public MedlineCitationSet createMedlineCitationSet() {
        return new MedlineCitationSet();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link CollectiveName }
     * 
     */
    public CollectiveName createCollectiveName() {
        return new CollectiveName();
    }

    /**
     * Create an instance of {@link AuthorList }
     * 
     */
    public AuthorList createAuthorList() {
        return new AuthorList();
    }

    /**
     * Create an instance of {@link GeneSymbol }
     * 
     */
    public GeneSymbol createGeneSymbol() {
        return new GeneSymbol();
    }

    /**
     * Create an instance of {@link GrantList }
     * 
     */
    public GrantList createGrantList() {
        return new GrantList();
    }

    /**
     * Create an instance of {@link Grant }
     * 
     */
    public Grant createGrant() {
        return new Grant();
    }

    /**
     * Create an instance of {@link PublicationType }
     * 
     */
    public PublicationType createPublicationType() {
        return new PublicationType();
    }

    /**
     * Create an instance of {@link SupplMeshName }
     * 
     */
    public SupplMeshName createSupplMeshName() {
        return new SupplMeshName();
    }

    /**
     * Create an instance of {@link MeshHeading }
     * 
     */
    public MeshHeading createMeshHeading() {
        return new MeshHeading();
    }

    /**
     * Create an instance of {@link QualifierName }
     * 
     */
    public QualifierName createQualifierName() {
        return new QualifierName();
    }

    /**
     * Create an instance of {@link PublicationTypeList }
     * 
     */
    public PublicationTypeList createPublicationTypeList() {
        return new PublicationTypeList();
    }

    /**
     * Create an instance of {@link Abstract }
     * 
     */
    public Abstract createAbstract() {
        return new Abstract();
    }

    /**
     * Create an instance of {@link Language }
     * 
     */
    public Language createLanguage() {
        return new Language();
    }

}
